# -*- coding: utf-8 -*-
"""BrittanicaPdfParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvClXvxBV-nOmUqpH0-5fxLI6yQJfens
"""

# This is a easier way to extract data from britannica website.
# There was a print option on the website that converts the content into pdfs
# So, we are using the pdfs to extract the text now

import pdfplumber
import os

def is_redundant(char_block):
    font_size_threshold = 8
    return char_block['size'] < font_size_threshold

pdf_files = ['Allegheny.pdf', 'Andrew Mellon.pdf', 'Henry John Heinz.pdf', 'Monongahela River.pdf', 'Monroeville.pdf', 'Pittsburgh Penguins.pdf', 'Pittsburgh Pirates.pdf', 'Pittsburgh Steelers.pdf', 'Pittsburgh Symphony.pdf', 'Pittsburgh glass.pdf', 'Pittsburgh.pdf']


for pdf_path in pdf_files:
    file_name = os.path.splitext(os.path.basename(pdf_path))[0]
    output_file_path = f'{file_name}.txt'

    with pdfplumber.open(pdf_path) as pdf:
        full_text = ""
        for page in pdf.pages:
            text = ""
            for char_block in page.chars:
                if not is_redundant(char_block):
                    text += char_block['text']

            full_text += text + "\n"

    stop_phrase = "Citation Information"
    if stop_phrase in full_text:
        full_text = full_text.split(stop_phrase)[0]

    with open(output_file_path, 'w', encoding='utf-8') as text_file:
        text_file.write(full_text)

    print(f"Extracted text saved to {output_file_path}")

