# -*- coding: utf-8 -*-
"""PostProcessingCmuEduText.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19w2jBDhjqxPgQbhJdlZaL9--pfGcDgx4
"""

def process_text(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()

    substring_to_remove = "CMU - Carnegie Mellon University Carnegie Mellon University    Search Search"
    text = text.replace(substring_to_remove, '')

    text = text.replace(f"{'-'*80}", f"\n{'-'*80}\n")
    lines = text.splitlines()
    cleaned_lines = []
    for line in lines:
        if '-'*80 in line:
            cleaned_lines.append(line)
        else:
            cleaned_lines.append(' '.join(line.split()))

    final_text = '\n'.join(cleaned_lines)

    with open('cmuedu.txt', 'w', encoding='utf-8') as output_file:
        output_file.write(final_text)

    return final_text

file_path = 'processed_text.txt'
process_text(file_path)

