# -*- coding: utf-8 -*-
"""CombineMarkdown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5ZfwTjuNu8xTAa7qVwdzXPGqN40zIQO
"""

import os
import glob
import pandas as pd
import json

def get_file_name(file_path):
    return os.path.splitext(os.path.basename(file_path))[0]

def process_csv_files(csv_files, markdown_lines):
    for file in csv_files:
        try:
            df = pd.read_csv(file)
            if 'section' in df.columns and 'text' in df.columns:
                file_name = get_file_name(file)
                markdown_lines.append(f"# {file_name}\n\n")

                for _, row in df.iterrows():
                    section = row['section']
                    text = row['text']
                    markdown_lines.append(f"## {section}\n")
                    markdown_lines.append(f"{text}\n\n")

            else:
                print(f"'section' or 'text' column not found in {file}. Skipping.")
        except pd.errors.EmptyDataError:
            print(f"Skipping empty file: {file}")
        except pd.errors.ParserError as e:
            print(f"Error parsing file: {file}. Error: {str(e)}")

    return markdown_lines

def process_txt_files(txt_files, markdown_lines):
    for file in txt_files:
        try:
            with open(file, 'r') as f:
                content = f.read().strip()

            file_name = get_file_name(file)
            markdown_lines.append(f"# {file_name}\n\n")
            markdown_lines.append(f"{content}\n\n")

        except Exception as e:
            print(f"Error reading file: {file}. {str(e)}")

    return markdown_lines

def process_json_files(json_files, markdown_lines):
    markdown_lines.append("# Pittsburgh Events\n\n")

    for file in json_files:
        try:
            with open(file, 'r') as f:
                data = json.load(f)

            if isinstance(data, list):
                for event in data:
                    event_name = event.get("event_name", "Unknown Event")
                    markdown_lines.append(f"## {event_name}\n")

                    for key, value in event.items():
                        if key != "event_name":
                            markdown_lines.append(f"**{key.capitalize()}**: {value}\n")

                    markdown_lines.append("\n")

            else:
                event_name = data.get("event_name", "Unknown Event")
                markdown_lines.append(f"## {event_name}\n")

                for key, value in data.items():
                    if key != "event_name":
                        markdown_lines.append(f"**{key.capitalize()}**: {value}\n")

                markdown_lines.append("\n")

        except Exception as e:
            print(f"Error reading file: {file}. {str(e)}")

    return markdown_lines

def process_special_txt_file(special_file, markdown_lines):
    markdown_lines.append("# More About Carnegie Mellon University\n\n")

    try:
        with open(special_file, 'r') as f:
            content = f.read().strip()

        chunks = content.split(f"{'-'*80}")
        for chunk in chunks:
            chunk = chunk.strip()
            if chunk:
                first_word = chunk.split()[0] if chunk.split() else "No Title"
                markdown_lines.append(f"## {first_word}\n")
                markdown_lines.append(f"{chunk}\n\n")

    except Exception as e:
        print(f"Error reading special file: {special_file}. {str(e)}")

    return markdown_lines

def generate_markdown_from_files(folder_path, special_file_name, output_md):
    markdown_lines = []
    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
    markdown_lines = process_csv_files(csv_files, markdown_lines)

    json_files = glob.glob(os.path.join(folder_path, "*.json"))
    markdown_lines = process_json_files(json_files, markdown_lines)

    txt_files = [f for f in glob.glob(os.path.join(folder_path, "*.txt")) if os.path.basename(f) != special_file_name]
    markdown_lines = process_txt_files(txt_files, markdown_lines)

    special_file = os.path.join(folder_path, special_file_name)
    markdown_lines = process_special_txt_file(special_file, markdown_lines)

    with open(output_md, 'w') as f:
        f.writelines(markdown_lines)

    print(f"Markdown file generated and saved as '{output_md}'")

folder_path = ""
special_file_name = "processed_text.txt"
output_md = "final_data.md"
generate_markdown_from_files(folder_path, special_file_name, output_md)

